-- Q1. What is the total revenue generated by male vs. female customers?
	select gender,sum(purchase_amount) from customer
	group by gender
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
	SELECT customer_id, AVG(purchase_amount) AS "Avg purchase amount"
	FROM customer
	WHERE discount_applied = 'Yes'
 	 AND purchase_amount > (
      SELECT AVG(purchase_amount) FROM customer
  	)
	GROUP BY customer_id;
-- Q3. Which are the top 5 products with the highest average review rating?
	select * from customer
	SELECT item_purchased, AVG(review_rating) AS avg_rating
	FROM customer
	GROUP BY item_purchased
	ORDER BY avg_rating DESC
	LIMIT 5;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
	SELECT shipping_type,
       AVG(purchase_amount) AS avg_purchase_amount
	FROM customer
	WHERE shipping_type IN ('Standard', 'Express')
	GROUP BY shipping_type;
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
	SELECT subscription_status,
       AVG(purchase_amount) AS avg_spend,
       SUM(purchase_amount) AS total_revenue,
       COUNT(*) AS total_orders
	FROM customer
	GROUP BY subscription_status;
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
	SELECT item_purchased,
       COUNT(*) AS total_purchases,
       SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
       100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) AS discount_percentage
	FROM customer
	GROUP BY item_purchased
	ORDER BY discount_percentage DESC
	LIMIT 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
	SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
	FROM customer
	GROUP BY customer_segment
	ORDER BY customer_count DESC;
-- Q8. What are the top 3 most purchased products within each category?
	SELECT category,
       item_purchased,
       purchase_count
	FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS rank_in_category
    FROM customer
    GROUP BY category, item_purchased
	) t
	WHERE rank_in_category <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
	SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Others'
    END AS customer_type,
    
    COUNT(*) AS total_customers,
    
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribed_customers,
    
    100.0 * SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) 
           / COUNT(*) AS subscription_rate
           
	FROM customer
	GROUP BY customer_type;
-- Q10. What is the revenue contribution of each age group? T
	SELECT 
    CASE 
        WHEN age < 18 THEN 'Under 18'
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS age_group,
    
    SUM(purchase_amount) AS total_revenue,
    
    100.0 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER () AS revenue_percentage

FROM customer
GROUP BY 
    CASE 
        WHEN age < 18 THEN 'Under 18'
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END
ORDER BY total_revenue DESC;